# [mgr]
# prepend_keymap = [
#
#     # plugin keybinds
#     { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files" },
#
#     # TODO: add additional g key mappings for quick directory jumping
#     # directory nav
#     { on = [ "g", "d" ], run = "cd ~/.dotfiles", desc = "cd Dots" },
#     { on = [ "g", "c" ], run = "cd ~/Cloud/",    desc = "cd Cloud" },
#     { on = [ "g", "n" ], run = "cd ~/Notes/",    desc = "cd Notes" },
#     { on = [ "g", "p" ], run = "cd ~/prj/",     desc = "cd prj" },
#     # { on = [ "g", "j" ], run = "cd '~/MEGA/00-09 System/00 System Management/00.00 JDex/'",   desc = "cd JDex" },
#
# ]

[mgr]

prepend_keymap = [
  { on = [
    "!",
  ], run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = [
    "c",
    "a",
  ], run = "plugin compress", desc = "Archive selected files" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "K", run = "arrow -50%", desc = "Move cursor up half page" },
  { on = "J", run = "arrow 50%", desc = "Move cursor down half page" },
  { on = "<A-k>", run = "arrow -5", desc = "Move cursor up half page" },
  { on = "<A-j>", run = "arrow 5", desc = "Move cursor down half page" },
  { on = [
    "s",
  ], run = "plugin searchjump --autocd", desc = "Flash" },
  { on = "S", run = "search --via=fd", desc = "Search files by name using fd" },
  { on = [
    "<C-y>",
  ], run = 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', desc = "Copy to clipboard" },
  { on = "A", run = "create --dir", desc = "Create a dir" },
  { on = [
    "g",
    "r",
  ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Root of Git Repo" },
  { on = "H", run = "tab_switch -1 --relative", desc = "Switch to the previous tab" },
  { on = "L", run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
  { on = "<", run = "tab_swap -1", desc = "Swap current tab with previous tab" },
  { on = ">", run = "tab_swap 1", desc = "Swap current tab with next tab" },
]

append_keymap = [
  { on = [
    "e",
  ], run = "open", desc = "Open the selected files" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Open the selected files interactively" },
]

[completion]
prepend_keymap = [
  { on = "<C-k>", run = "arrow -1", desc = "Move cursor up" },
  { on = "<C-j>", run = "arrow 1", desc = "Move cursor down" },
]
