"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[flavor]
dark = "catppuccin-macchiato"

[icon]
append_dirs = [
    { name = "Archive", text = "" },
    { name = "Cloud", text = "" },
    { name = "Dev", text = "" },
    { name = "Notes", text = "" },
    { name = "Audio", text = "" },
    { name = "Media", text = "󱧺" },
    { name = "Games", text = "󰖺" },
    { name = "JDex", text = "󱪹" },
]
