customCommands:
  - key: "C"
    command: 'git commit -m "{{ .Form.Type }}{{if .Form.Scope}}({{ .Form.Scope }}){{end}}: {{ .Form.Emoji }} {{ .Form.Description }}"'
    description: "conventional commit"
    context: "files"
    prompts:
      - type: "menu"
        title: "Select the type of change you are committing."
        key: "Type"
        options:
          - name: "Feature"
            description: "a new feature"
            value: "feat"
          - name: "Fix"
            description: "a bug fix"
            value: "fix"
          - name: "Documentation"
            description: "Documentation only changes"
            value: "docs"
          - name: "Styles"
            description: "Styling changes (white-space, formatting, etc)"
            value: "style"
          - name: "Code Refactoring"
            description: "Refactoring code"
            value: "refactor"
          - name: "Performance Improvements"
            description: "Performance improvements"
            value: "perf"
          - name: "Tests"
            description: "Test additions or fixes"
            value: "test"
          - name: "Builds"
            description: "Build system or dependency changes"
            value: "build"
          - name: "Continuous Integration"
            description: "CI configuration changes"
            value: "ci"
          - name: "Chores"
            description: "Other non-code changes"
            value: "chore"
          - name: "Reverts"
            description: "Reverting changes"
            value: "revert"
      - type: "menu"
        title: "Choose the emoji for this commit type."
        key: "Emoji"
        options:
          - name: "ðŸŽ¨ Improve structure / format of the code."
            value: ":art:"
          - name: "âš¡ï¸ Improve performance."
            value: ":zap:"
          - name: "ðŸ”¥ Remove code or files."
            value: ":fire:"
          - name: "ðŸ› Fix a bug."
            value: ":bug:"
          - name: "ðŸš‘ï¸ Critical hotfix."
            value: ":ambulance:"
          - name: "âœ¨ Introduce new features."
            value: ":sparkles:"
          - name: "ðŸ“ Add or update documentation."
            value: ":memo:"
          - name: "ðŸš€ Deploy stuff."
            value: ":rocket:"
          - name: "ðŸ’„ Add or update the UI and style files."
            value: ":lipstick:"
          - name: "ðŸŽ‰ Begin a project."
            value: ":tada:"
          - name: "âœ… Add, update, or pass tests."
            value: ":white_check_mark:"
          - name: "ðŸ”’ï¸ Fix security or privacy issues."
            value: ":lock:"
          - name: "ðŸ” Add or update secrets."
            value: ":closed_lock_with_key:"
          - name: "ðŸ”– Release / Version tags."
            value: ":bookmark:"
          - name: "ðŸš¨ Fix compiler / linter warnings."
            value: ":rotating_light:"
          - name: "ðŸš§ Work in progress."
            value: ":construction:"
          - name: "ðŸ’š Fix CI Build."
            value: ":green_heart:"
          - name: "â¬‡ï¸ Downgrade dependencies."
            value: ":arrow_down:"
          - name: "â¬†ï¸ Upgrade dependencies."
            value: ":arrow_up:"
          - name: "ðŸ“Œ Pin dependencies to specific versions."
            value: ":pushpin:"
          - name: "ðŸ‘· Add or update CI build system."
            value: ":construction_worker:"
          - name: "ðŸ“ˆ Add or update analytics or track code."
            value: ":chart_with_upwards_trend:"
          - name: "â™»ï¸ Refactor code."
            value: ":recycle:"
          - name: "âž• Add a dependency."
            value: ":heavy_plus_sign:"
          - name: "âž– Remove a dependency."
            value: ":heavy_minus_sign:"
          - name: "ðŸ”§ Add or update configuration files."
            value: ":wrench:"
          - name: "ðŸ”¨ Add or update development scripts."
            value: ":hammer:"
          - name: "ðŸŒ Internationalization and localization."
            value: ":globe_with_meridians:"
          - name: "âœï¸ Fix typos."
            value: ":pencil2:"
          - name: "ðŸ’© Write bad code that needs to be improved."
            value: ":poop:"
          - name: "âªï¸ Revert changes."
            value: ":rewind:"
          - name: "ðŸ”€ Merge branches."
            value: ":twisted_rightwards_arrows:"
          - name: "ðŸ“¦ï¸ Add or update compiled files or packages."
            value: ":package:"
          - name: "ðŸ‘½ï¸ Update code due to external API changes."
            value: ":alien:"
          - name: "ðŸšš Move or rename resources (e.g.: files, paths, routes)."
            value: ":truck:"
          - name: "ðŸ“„ Add or update license."
            value: ":page_facing_up:"
          - name: "ðŸ’¥ Introduce breaking changes."
            value: ":boom:"
          - name: "ðŸ± Add or update assets."
            value: ":bento:"
          - name: "â™¿ï¸ Improve accessibility."
            value: ":wheelchair:"
          - name: "ðŸ’¡ Add or update comments in source code."
            value: ":bulb:"
          - name: "ðŸ» Write code drunkenly."
            value: ":beers:"
          - name: "ðŸ’¬ Add or update text and literals."
            value: ":speech_balloon:"
          - name: "ðŸ—ƒï¸ Perform database related changes."
            value: ":card_file_box:"
          - name: "ðŸ”Š Add or update logs."
            value: ":loud_sound:"
          - name: "ðŸ”‡ Remove logs."
            value: ":mute:"
          - name: "ðŸ‘¥ Add or update contributor(s)."
            value: ":busts_in_silhouette:"
          - name: "ðŸš¸ Improve user experience / usability."
            value: ":children_crossing:"
          - name: "ðŸ—ï¸ Make architectural changes."
            value: ":building_construction:"
          - name: "ðŸ“± Work on responsive design."
            value: ":iphone:"
          - name: "ðŸ¤¡ Mock things."
            value: ":clown_face:"
          - name: "ðŸ¥š Add or update an easter egg."
            value: ":egg:"
          - name: "ðŸ™ˆ Add or update a .gitignore file."
            value: ":see_no_evil:"
          - name: "ðŸ“¸ Add or update snapshots."
            value: ":camera_flash:"
          - name: "âš—ï¸ Perform experiments."
            value: ":alembic:"
          - name: "ðŸ”ï¸ Improve SEO."
            value: ":mag:"
          - name: "ðŸ·ï¸ Add or update types."
            value: ":label:"
          - name: "ðŸŒ± Add or update seed files."
            value: ":seedling:"
          - name: "ðŸš© Add, update, or remove feature flags."
            value: ":triangular_flag_on_post:"
          - name: "ðŸ¥… Catch errors."
            value: ":goal_net:"
          - name: "ðŸ’« Add or update animations and transitions."
            value: ":dizzy:"
          - name: "ðŸ—‘ï¸ Deprecate code that needs to be cleaned up."
            value: ":wastebasket:"
          - name: "ðŸ›‚ Work on code related to authorization, roles and permissions."
            value: ":passport_control:"
          - name: "ðŸ©¹ Simple fix for a non-critical issue."
            value: ":adhesive_bandage:"
          - name: "ðŸ§ Data exploration/inspection."
            value: ":monocle_face:"
          - name: "âš°ï¸ Remove dead code."
            value: ":coffin:"
          - name: "ðŸ§ª Add a failing test."
            value: ":test_tube:"
          - name: "ðŸ‘” Add or update business logic."
            value: ":necktie:"
          - name: "ðŸ©º Add or update healthcheck."
            value: ":stethoscope:"
          - name: "ðŸ§± Infrastructure related changes."
            value: ":bricks:"
      - type: "menuFromCommand"
        title: "Select a scope:"
        command: >
          bash -c "jq -r '.\"conventionalCommits.scopes\"[]' \"$(git rev-parse --show-toplevel)/.vscode/settings.json\""
        filter: "^(.*)$"
        valueFormat: "{{ .group_0 }}"
        labelFormat: "{{ .group_0 | cyan }}"
        key: "Scope"
      - type: "input"
        title: "Enter the short description of the change."
        key: "Description"
      - type: "confirm"
        title: "Is the commit message correct?"
        body: "{{ .Form.Type }}{{if .Form.Scope}}({{ .Form.Scope }}){{end}}: {{ .Form.Emoji }} {{ .Form.Description }}"

